# Generated by Django 4.2.7 on 2023-11-01 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(default='Nome Padrão', max_length=255)),
                ('Sobrenome', models.CharField(default='Sobrenome Padrão', max_length=255)),
                ('Data_nascimento', models.DateField(default=datetime.datetime(2023, 11, 1, 17, 47, 51, 337694), null=True)),
                ('endereco', models.TextField(default='')),
                ('cidade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='angeline.cidade')),
            ],
        ),
    ]
