# Generated by Django 4.2.6 on 2023-10-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0002_pessoa_cpf_pessoa_date_added_pessoa_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='date_added',
        ),
    ]
