# Generated by Django 4.2.7 on 2023-11-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0002_categoria_livro_remove_pessoa_cidade_delete_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='linkimg',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='pdf',
        ),
    ]
