# Generated by Django 4.2.7 on 2023-11-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0003_remove_livro_linkimg_remove_livro_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='angeline.categoria'),
        ),
    ]
