# Generated by Django 4.2.7 on 2023-11-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0004_alter_livro_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
    ]
