# Generated by Django 4.2.7 on 2023-11-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0005_remove_livro_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.IntegerField(null=True),
        ),
    ]
